import type { Metadata } from "next";
import { Geist, Geist_Mono, Cardo, Gloock, Joti_One, Caprasimo, Hanuman, Inknut_Antiqua } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Link } from "@/i18n/navigation";
import { ThemeProvider } from "@/compo-provider/theme-provider";
import Header from "./header/header";
import Footer from "./footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cardo = Cardo({
  variable: "--font-cardo",
  subsets: ["latin"],
  weight: "400"
})
const hanuman = Hanuman({
  variable: "--font-hanuman",
  subsets: ["latin"],
  weight: "400"
})

const inknut_Antiqua = Inknut_Antiqua({
  variable: "--font-inknut_Antiqua",
  subsets: ["latin"],
  weight: "400"
})

const joti_One = Joti_One({
  variable: "--font-joti_One",
  subsets: ["latin"],
  weight: "400"
})

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  subsets: ["latin"],
  weight: "400"
})

const gloock = Gloock({
  variable: "--font-gloock",
  subsets: ["latin"],
  weight: "400"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Détermination de la langue cible
  const oppositeLocale = locale === "en" ? "fr" : "en";

  return (
    <html lang={locale} className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} ${cardo.variable} ${gloock.variable} ${joti_One.variable} ${caprasimo.variable} ${hanuman.variable} ${inknut_Antiqua.variable} antialiased`}>
        <link
          rel="stylesheet"
          type="text/css"

          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />

        <NextIntlClientProvider locale={locale}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <Footer/>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
